// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enumusingproto/proto/enumexample.proto

package enumexample

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IsSuccessFull int32

const (
	IsSuccessFull_UNKOWN IsSuccessFull = 0
	IsSuccessFull_TRUE   IsSuccessFull = 1
	IsSuccessFull_FALSE  IsSuccessFull = 2
)

var IsSuccessFull_name = map[int32]string{
	0: "UNKOWN",
	1: "TRUE",
	2: "FALSE",
}

var IsSuccessFull_value = map[string]int32{
	"UNKOWN": 0,
	"TRUE":   1,
	"FALSE":  2,
}

func (x IsSuccessFull) String() string {
	return proto.EnumName(IsSuccessFull_name, int32(x))
}

func (IsSuccessFull) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5b213afc71f04c77, []int{0}
}

type CompileData struct {
	Check                IsSuccessFull `protobuf:"varint,1,opt,name=check,proto3,enum=IsSuccessFull" json:"check,omitempty"`
	ErrorCode            int32         `protobuf:"varint,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	SuccessCode          int32         `protobuf:"varint,3,opt,name=SuccessCode,proto3" json:"SuccessCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CompileData) Reset()         { *m = CompileData{} }
func (m *CompileData) String() string { return proto.CompactTextString(m) }
func (*CompileData) ProtoMessage()    {}
func (*CompileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b213afc71f04c77, []int{0}
}

func (m *CompileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompileData.Unmarshal(m, b)
}
func (m *CompileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompileData.Marshal(b, m, deterministic)
}
func (m *CompileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompileData.Merge(m, src)
}
func (m *CompileData) XXX_Size() int {
	return xxx_messageInfo_CompileData.Size(m)
}
func (m *CompileData) XXX_DiscardUnknown() {
	xxx_messageInfo_CompileData.DiscardUnknown(m)
}

var xxx_messageInfo_CompileData proto.InternalMessageInfo

func (m *CompileData) GetCheck() IsSuccessFull {
	if m != nil {
		return m.Check
	}
	return IsSuccessFull_UNKOWN
}

func (m *CompileData) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CompileData) GetSuccessCode() int32 {
	if m != nil {
		return m.SuccessCode
	}
	return 0
}

func init() {
	proto.RegisterEnum("IsSuccessFull", IsSuccessFull_name, IsSuccessFull_value)
	proto.RegisterType((*CompileData)(nil), "CompileData")
}

func init() {
	proto.RegisterFile("enumusingproto/proto/enumexample.proto", fileDescriptor_5b213afc71f04c77)
}

var fileDescriptor_5b213afc71f04c77 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0xcd, 0x2b, 0xcd,
	0x2d, 0x2d, 0xce, 0xcc, 0x4b, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x87, 0x90, 0x20, 0xc1, 0xd4,
	0x8a, 0xc4, 0xdc, 0x82, 0x9c, 0x54, 0x3d, 0xb0, 0x88, 0x52, 0x31, 0x17, 0xb7, 0x73, 0x7e, 0x6e,
	0x41, 0x66, 0x4e, 0xaa, 0x4b, 0x62, 0x49, 0xa2, 0x90, 0x0a, 0x17, 0x6b, 0x72, 0x46, 0x6a, 0x72,
	0xb6, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x9f, 0x11, 0x9f, 0x9e, 0x67, 0x71, 0x70, 0x69, 0x72, 0x72,
	0x6a, 0x71, 0xb1, 0x5b, 0x69, 0x4e, 0x4e, 0x10, 0x44, 0x52, 0x48, 0x86, 0x8b, 0xd3, 0xb5, 0xa8,
	0x28, 0xbf, 0xc8, 0x39, 0x3f, 0x25, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x08, 0x21, 0x20,
	0xa4, 0xc0, 0xc5, 0x0d, 0xd5, 0x03, 0x96, 0x67, 0x06, 0xcb, 0x23, 0x0b, 0x69, 0x19, 0x70, 0xf1,
	0xa2, 0x98, 0x2b, 0xc4, 0xc5, 0xc5, 0x16, 0xea, 0xe7, 0xed, 0x1f, 0xee, 0x27, 0xc0, 0x20, 0xc4,
	0xc1, 0xc5, 0x12, 0x12, 0x14, 0xea, 0x2a, 0xc0, 0x28, 0xc4, 0xc9, 0xc5, 0xea, 0xe6, 0xe8, 0x13,
	0xec, 0x2a, 0xc0, 0x94, 0xc4, 0x06, 0x76, 0xad, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x66, 0xf6,
	0x82, 0xdf, 0xd7, 0x00, 0x00, 0x00,
}
