// Code generated by protoc-gen-go. DO NOT EDIT.
// source: expert/services/proto/search.proto

package search

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	PhoneNumber          int64    `protobuf:"varint,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbf1d4648b8aa4eb, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetPhoneNumber() int64 {
	if m != nil {
		return m.PhoneNumber
	}
	return 0
}

type SearchResponse struct {
	PhoneNumber          int64    `protobuf:"varint,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode           int32    `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbf1d4648b8aa4eb, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetPhoneNumber() int64 {
	if m != nil {
		return m.PhoneNumber
	}
	return 0
}

func (m *SearchResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SearchResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

func init() { proto.RegisterFile("expert/services/proto/search.proto", fileDescriptor_dbf1d4648b8aa4eb) }

var fileDescriptor_dbf1d4648b8aa4eb = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x45, 0x65, 0x2a, 0x40, 0xbc, 0xd2, 0x22, 0x79, 0xb2, 0x58, 0x08, 0x99, 0x32, 0x25, 0xa8,
	0x7c, 0x01, 0xca, 0xce, 0xe0, 0x7e, 0x40, 0xe5, 0xba, 0x57, 0x84, 0x21, 0xb6, 0xf1, 0x7b, 0x41,
	0x7c, 0x3e, 0x92, 0xa3, 0x0c, 0xd9, 0x3a, 0x9e, 0x23, 0x5d, 0xe9, 0x1e, 0xaa, 0xf1, 0x97, 0x90,
	0xa5, 0x63, 0xe4, 0xdf, 0x6f, 0x0f, 0xee, 0x52, 0x8e, 0x12, 0x3b, 0x86, 0xcb, 0x7e, 0x68, 0x0b,
	0xd4, 0x07, 0xda, 0x1d, 0x0b, 0x5b, 0xfc, 0x4c, 0x60, 0xd1, 0xaf, 0xf4, 0x98, 0x86, 0x18, 0x70,
	0x0a, 0xd3, 0x78, 0x46, 0x36, 0xaa, 0x52, 0xcd, 0xc6, 0x6e, 0x8b, 0xfb, 0x2c, 0xaa, 0x0e, 0xb4,
	0x5f, 0x36, 0x9c, 0x62, 0x60, 0x5c, 0x31, 0xd2, 0x86, 0xee, 0x47, 0x30, 0xbb, 0x2f, 0x98, 0x9b,
	0x4a, 0x35, 0x0f, 0x76, 0x41, 0xfd, 0x42, 0x5b, 0x16, 0x27, 0x13, 0x9f, 0x7c, 0xbc, 0xc0, 0x6c,
	0x2a, 0xd5, 0xdc, 0x5a, 0x9a, 0x55, 0x1f, 0x2f, 0x38, 0x7c, 0xd0, 0xae, 0xcf, 0x70, 0x82, 0xe3,
	0x1c, 0xa2, 0xdf, 0x96, 0xd3, 0x7d, 0x0c, 0xe2, 0xbc, 0xe8, 0x7d, 0xbb, 0x8a, 0x78, 0x7e, 0x6a,
	0xd7, 0x07, 0xcf, 0x77, 0xa5, 0xf6, 0xfd, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xec, 0x28, 0x02, 0xcc,
	0x13, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CreateServiceClient is the client API for CreateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreateServiceClient interface {
	SearchContact(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type createServiceClient struct {
	cc *grpc.ClientConn
}

func NewCreateServiceClient(cc *grpc.ClientConn) CreateServiceClient {
	return &createServiceClient{cc}
}

func (c *createServiceClient) SearchContact(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/CreateService/SearchContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateServiceServer is the server API for CreateService service.
type CreateServiceServer interface {
	SearchContact(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterCreateServiceServer(s *grpc.Server, srv CreateServiceServer) {
	s.RegisterService(&_CreateService_serviceDesc, srv)
}

func _CreateService_SearchContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateServiceServer).SearchContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreateService/SearchContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateServiceServer).SearchContact(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CreateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CreateService",
	HandlerType: (*CreateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchContact",
			Handler:    _CreateService_SearchContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expert/services/proto/search.proto",
}
