// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/proto/search.proto

package search

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	PhoneNumber          int64    `protobuf:"varint,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_054df2eebb79118d, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetPhoneNumber() int64 {
	if m != nil {
		return m.PhoneNumber
	}
	return 0
}

type SearchResponse struct {
	PhoneNumber          int64    `protobuf:"varint,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode           int32    `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_054df2eebb79118d, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetPhoneNumber() int64 {
	if m != nil {
		return m.PhoneNumber
	}
	return 0
}

func (m *SearchResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SearchResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

func init() { proto.RegisterFile("services/proto/search.proto", fileDescriptor_054df2eebb79118d) }

var fileDescriptor_054df2eebb79118d = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xb1, 0x6e, 0x83, 0x30,
	0x14, 0x45, 0xe5, 0xa2, 0xb6, 0xea, 0xa3, 0x50, 0xc9, 0x93, 0xd5, 0x0e, 0x25, 0x4c, 0x4c, 0x10,
	0x91, 0x2f, 0x88, 0xd8, 0x33, 0x98, 0x0f, 0x40, 0xc6, 0x3c, 0x85, 0x0c, 0xd8, 0xc4, 0xcf, 0xe4,
	0xfb, 0x23, 0x19, 0x31, 0xb0, 0x65, 0x3c, 0x47, 0xba, 0xd2, 0x3d, 0xf0, 0x47, 0xe8, 0x1e, 0x37,
	0x8d, 0x54, 0xcd, 0xce, 0x7a, 0x5b, 0x11, 0x2a, 0xa7, 0xc7, 0x32, 0x40, 0x5e, 0x43, 0xd2, 0x06,
	0x96, 0x78, 0x5f, 0x90, 0x3c, 0x3f, 0xc0, 0xf7, 0x3c, 0x5a, 0x83, 0x9d, 0x59, 0xa6, 0x1e, 0x9d,
	0x60, 0x19, 0x2b, 0x22, 0x19, 0x07, 0x77, 0x09, 0x2a, 0x37, 0x90, 0x6e, 0x1b, 0x9a, 0xad, 0x21,
	0x7c, 0x61, 0xc4, 0x05, 0x7c, 0x4e, 0x48, 0xa4, 0xae, 0x28, 0xde, 0x32, 0x56, 0x7c, 0xc9, 0x0d,
	0xf9, 0x3f, 0xc4, 0xe4, 0x95, 0x5f, 0xa8, 0xd3, 0x76, 0x40, 0x11, 0x65, 0xac, 0x78, 0x97, 0xb0,
	0xaa, 0xc6, 0x0e, 0x58, 0x9f, 0x21, 0x69, 0x1c, 0x2a, 0x8f, 0xed, 0x1a, 0xc2, 0x8f, 0xdb, 0xe9,
	0xc6, 0x1a, 0xaf, 0xb4, 0xe7, 0x69, 0xb9, 0x8b, 0xf8, 0xfd, 0x29, 0xf7, 0x07, 0xfb, 0x8f, 0x50,
	0x7b, 0x7a, 0x06, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x85, 0x42, 0x49, 0x0c, 0x01, 0x00, 0x00,
}
